# Generated by Django 5.2.1 on 2025-11-21 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.ImageField(upload_to='iconos_perfil/')),
            ],
            options={
                'db_table': 'imagenes',
            },
        ),
        migrations.CreateModel(
            name='RolUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rol_usuario',
            },
        ),
        migrations.CreateModel(
            name='Rutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('sug_semanas_em', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'rutina',
            },
        ),
        migrations.CreateModel(
            name='TipoAlerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tipos_alertas',
            },
        ),
        migrations.CreateModel(
            name='TipoLectura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tipo_lectura',
            },
        ),
        migrations.CreateModel(
            name='TipoTema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tipo_tema',
            },
        ),
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('nivel_esfuerzo', models.SmallIntegerField()),
                ('sug_semanas', models.SmallIntegerField()),
                ('categoria', models.CharField(max_length=50, null=True)),
                ('animacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.imagen')),
            ],
            options={
                'db_table': 'ejercicios',
            },
        ),
        migrations.CreateModel(
            name='CrearRutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.SmallIntegerField()),
                ('repeticiones', models.SmallIntegerField()),
                ('tiempo_seg', models.SmallIntegerField()),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ejercicio')),
                ('rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.rutina')),
            ],
            options={
                'db_table': 'crear_rutina',
            },
        ),
        migrations.CreateModel(
            name='ContenidoEducativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('texto', models.TextField()),
                ('urls_img', models.TextField(blank=True, null=True)),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tipotema')),
            ],
            options={
                'db_table': 'contenido_educativo',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('ap_pat', models.CharField(max_length=50)),
                ('ap_mat', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('semana_embarazo', models.SmallIntegerField(blank=True, null=True)),
                ('codigo_vinculacion', models.CharField(blank=True, max_length=10, null=True)),
                ('estado', models.BooleanField(default=False)),
                ('contrasena', models.CharField(max_length=128, null=True)),
                ('imagen_perfil', models.TextField(blank=True, null=True)),
                ('rol', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.rolusuario')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='RutinasGuardados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_guardado', models.DateTimeField(auto_now_add=True)),
                ('rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.rutina')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
            options={
                'db_table': 'rutina_guardados',
            },
        ),
        migrations.AddField(
            model_name='rutina',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario'),
        ),
        migrations.CreateModel(
            name='Retroalimentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.TextField()),
                ('rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.rutina')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
            options={
                'db_table': 'retroalimentacion',
            },
        ),
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField()),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ejercicio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
            options={
                'db_table': 'resenas',
            },
        ),
        migrations.CreateModel(
            name='Rangos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rbpm_inferior', models.SmallIntegerField()),
                ('rbpm_superior', models.SmallIntegerField()),
                ('rox_inferior', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rox_superior', models.DecimalField(decimal_places=2, max_digits=5)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
            options={
                'db_table': 'rangos',
            },
        ),
        migrations.CreateModel(
            name='Lectura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('lectura_bpm', models.SmallIntegerField()),
                ('lectura_ox', models.DecimalField(decimal_places=2, max_digits=5)),
                ('temperatura', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.tipolectura')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
            options={
                'db_table': 'lecturas',
            },
        ),
        migrations.CreateModel(
            name='HistorialRutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('finalizada', models.BooleanField(default=False)),
                ('avg_oxigeno', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('avg_bpm', models.SmallIntegerField(blank=True, null=True)),
                ('calorias', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('tiempo', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(max_length=50)),
                ('rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.rutina')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
            options={
                'db_table': 'historial_rutina',
            },
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario'),
        ),
        migrations.CreateModel(
            name='ContactoEmerg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('ap_pat', models.CharField(max_length=50)),
                ('ap_mat', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
            options={
                'db_table': 'contacto_emerg',
            },
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('fecha_alerta', models.DateTimeField(auto_now_add=True)),
                ('lectura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.lectura')),
                ('tipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.tipoalerta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
            options={
                'db_table': 'alertas',
            },
        ),
    ]
