# Generated by Django 5.2.1 on 2025-11-26 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_usuario_imagen_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagen',
            name='proposito',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
