# Generated by Django 5.2.1 on 2025-11-26 07:16

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_imagen_proposito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='url',
            field=models.ImageField(upload_to=api.models.ruta_por_proposito),
        ),
    ]
