# Generated by Django 5.2.1 on 2025-11-26 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_imagen_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutina',
            name='icono_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.imagen'),
        ),
    ]
