# Generated by Django 5.2.1 on 2025-11-27 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rutina_icono_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rutina',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
