# Generated by Django 5.2.1 on 2025-11-28 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_rutina_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutina',
            name='es_publica',
            field=models.BooleanField(default=False),
        ),
    ]
