# Generated by Django 5.2.1 on 2025-11-29 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rutina_es_publica'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejercicio',
            name='repeticiones_default',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='series_default',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='tiempo_seg_default',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
