# Generated by Django 5.2.1 on 2025-12-01 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_ejercicio_repeticiones_default_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rutina',
            old_name='icono_id',
            new_name='icono',
        ),
        migrations.AlterField(
            model_name='rutina',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
