# Generated by Django 5.2.1 on 2025-12-02 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_icono_id_rutina_icono_alter_rutina_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historialrutina',
            old_name='calorias',
            new_name='temperatura',
        ),
    ]
