# Generated by Django 5.2.1 on 2025-12-02 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_calorias_historialrutina_temperatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='fecha_inicio_embarazo',
            field=models.DateField(blank=True, help_text='Fecha estimada de inicio del embarazo (Semana 0 + 0 días).', null=True),
        ),
    ]
